language: node_js
node_js:
- "11"
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: users
  - DEFAULT_INCREMENT: patch
  # SAUCE_USERNAME
  - secure: CphQrl3w/0STo1fHwergdtsNBbNpMXFMzR99V60lp/btWKtVdFeTF98kIeN6Ss+uda+QSpbxYzNNkJJDkXcPqCGilg7gEFMpCKygECxBdJv0caVrwCqxVNCFH5gt4+SL0MQLGqGAwaQTPHtpkvyB9yQy9gJ61WcBJlGehFNgHsXNl4pqh3Z1iUNP0/scoswQ/sKYLHFSlwSMM7/qAiSEB0YA5FiB+ia7RYLAFUCFmbaSIBodX82du1r4ZV36qkXExH9e9mVKQw5nvAtUOvMSssIkMwyopxCch+2I7b6ZA1n3NhAlrgwsODQbWt5ylvEqSgsl7Fn+Zz4BqMXBuQ/2h3A8D8e6NVPblt2iZRoPiC03SIImqUqhweLfHNa8E+zJIAafC6tS4RVxQ9RAPPuBVCLhShbtqoZPDuWoczVDOpyhDyyho5sQzGecGHuhE2lkF2J03E7kTn+uOEC5DZg8H2zGsL1IckrIAmeqwYYRx/6Hol7jXbH9bDipbq85HZB8/SVvF2xFs+nwepbCvnPcoBXEPie3EviPVkLIjNF2dT3pMAxadobP1dCujuGOm3Nrgl7TTCcncCposSmLE/pQxoeXEh2y/W6vg1Dh5ddLNiPTAkpKSR6mRBdZtuuzn+DLvDKxHx0kSNvEtgresq651dEhZbk4WP63FWbOjJUTpz4=
  # SAUCE_ACCESS_KEY
  - secure: nSRejAOMhdgjZ49lLdwccF2ETOJGvl0l4Td4HGXZwhDilEr7AlSGiEP/jbvwcCx2IeauXLnP23MB5ozqFM2GjlApaFAJWuhyMJzeUJTdat1+v96jGQ6JXFLEvt7dcaFNb5xC6jTVm3pSJOLviEvpkphpwkBDDeqLyiq0x9wa0niCyLwSjdyldhwdcEol0bnXyY/LuVYOJEEClm7Un0XASahr+UEl37PmiCJa14PIBG2pemW9z0eXB12E1Vc22psAcamM2Oijnk+j1UlEaoQLB8YuzEAAcqSwo5vu3yvgPwh7g0VCK2RNobYUfALh0wW9s6czB2Ps4A9ZhKeVbxv/FM0/vRUHcqw/dtIbvFKsUJy8amriiNZDcgfKVpz0YIM++xB0aCd2Te2NUbfjwajiJKdw9yr0IiI6px4q4o06ae0n2MiEfGF2eTBXgAmWz8wnfmL2iLg252b3xtHsrUKCgwim/MD63BMP4GeKO1Q0eJ2Kp3Ug8KHFbPwUW2LuN4FabcVKSd9OiGPkKfrMVc4MG2xiSRwn60Buw/kgB+OjtOKZW8j1Bx2Co1aRB5aW5Hy1IFRqC5M+pZT+O2xP9Sm5CYf5foiWGDVmCknayCJJ/LpjTmvvfcRv11EvQDiDU23XZcYUtI6v+Py6t7/M60L9D8AbwjBXJGAfAmaC8AKsJ1M=
  # GITHUB_RELEASE_TOKEN (fe14......a5bd)
  - secure: ISe/6HDGG50hfWyDqu6h6HLse9jSx70oYRoNw825oHIhb6lxRxK3HfmuPLaOqplDqqCqv84uMFzzP+yczdqy4vaEzzGoEZ9dlFTq7ARVOAX0WQwRBKFNZIBDqTrbfgYFw7ZYeHMAFe3M8O1Rxpqp1CP5KiIiMRcXm1tNxwi7imECO6/Dccf0Gm0fv+kCSafzyBBuRkg0GSrbctkvHJW0RoSxkPKYRY6GaDZVUZofeq4CcowBPmri85P9SFtSTGDLycY3vcaL527xDAG8ItbxA8Lf+soEL0ZcDnngjs03O7lolZMr0ht05Uv7cdjiibMgWUC0AKu//pRiB50Mgmwr6T2vmxh2u770y/SoNgbGVYpttXW1cO/Da1q5VVzlVOL+ThSXCxXfvdHcs837Vd1SFhm9nekVQ6FXl29nB+wW2vGhEvAzMOAb3SLjmyw8X+/9z+0sIz/HsaO86+POKw+bPcn2fYChorQQe+9v9JLecd6BVrDlO9CflG9YC7EA3fX9dWi47R1vsnEwBTkl8rx99zqOjOMjHgbL7HQ6kt+sVXHpg6C8pBb7+srmsx11p6Y6gdixUuTsNWIWnYDMlLEuJJaiqp3JICzXupUkenxrw7AzfaITECR36fE8mcDFzPy1SFEQhDxwbSjDHdebLuCoX0Iq7Lipa3z2yOaQvmGrsN8=